-- Your SQL goes here
ALTER TABLE sale ALTER COLUMN id_product SET NOT NULL;
ALTER TABLE sale ALTER COLUMN id_currency SET NOT NULL;
ALTER TABLE sale ALTER COLUMN amount SET NOT NULL;
ALTER TABLE sale ALTER COLUMN date_sale SET NOT NULL;